## 00. Pytorch Fundamentals


In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.1+cu130


In [8]:
print("Hello, I'm excited to learn PyTorch")

Hello, I'm excited to learn PyTorch


## Introduction to Tensors



### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`

In [70]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [71]:
# ndim = number of dimensions
scalar.ndim

0

In [72]:
# Get tensor back as Python int
scalar.item()

7

In [73]:
# Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [74]:
vector.ndim

1

In [75]:
vector.shape

torch.Size([2])

In [76]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [77]:
MATRIX.ndim


2

In [78]:
MATRIX[1]

tensor([ 9, 10])

In [79]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [80]:
TENSOR.ndim

3

In [81]:
TENSOR.shape

torch.Size([1, 3, 3])

In [82]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

![Tensor](images\tensor.png)

In [83]:
PRACTICE_TENSOR = torch.tensor([[[6,7,9,1],
                                 [5,3,2,0]],
                                [[1,1,1,1],
                                 [2,2,2,2]]])
PRACTICE_TENSOR

tensor([[[6, 7, 9, 1],
         [5, 3, 2, 0]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2]]])

In [84]:
PRACTICE_TENSOR.ndim

3

In [85]:
PRACTICE_TENSOR.shape

torch.Size([2, 2, 4])

### Random Tensors

Why Random tensors?

Random tensors are important because the wat many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> Update random numbers -> Look at data -> Update random numbers`

In [86]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9998, 0.5944, 0.6541, 0.0337],
        [0.1716, 0.3336, 0.5782, 0.0600],
        [0.2846, 0.2007, 0.5014, 0.3139]])

In [87]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, Width, Color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [88]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [89]:
# Create tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [90]:
ones.dtype

torch.float32

In [91]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like 

In [92]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you will run into with PyTorch & deep learning:
1. Tensors are not the right datatype
2. Tensors are not the right shape
3. Tensors are not on the right device

In [94]:
# FLoat 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32, float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients 
float_32_tensor

tensor([3., 6., 9.])

In [95]:
float_32_tensor.dtype

torch.float32

In [96]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [97]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [98]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [99]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. To get datatype from a tensor, can use `tensor.dtype`
2. To get shape from a tensor, can use `tensor.shape`
3. To get device from a tensor, can use `tensor.device`

In [100]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1429, 0.2596, 0.3507, 0.6683],
        [0.4601, 0.9545, 0.1936, 0.8199],
        [0.3752, 0.6261, 0.6456, 0.1400]])

In [101]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device that tensoris on: {some_tensor.device}")


tensor([[0.1429, 0.2596, 0.3507, 0.6683],
        [0.4601, 0.9545, 0.1936, 0.8199],
        [0.3752, 0.6261, 0.6456, 0.1400]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device that tensoris on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication 

In [102]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [103]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [104]:
tensor

tensor([1, 2, 3])

In [105]:
# subtract
tensor - 10

tensor([-9, -8, -7])

In [106]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [107]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The inner dimensions must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resultin matrix has the shape of the **outer dimensions**"
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [108]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.5215, 0.4297],
        [0.4318, 0.3998]])

In [109]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [110]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [111]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [112]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 382 μs


In [113]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 15.6 ms
Wall time: 130 μs


tensor(14)

### One of the most common errors in deep learning: shape errors


In [114]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axis or dimensions of a given tensor.


In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput: shape: {output.shape}")



Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]) (same shape), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output: shape: torch.Size([3, 3])


## Finding the min, max, mean, sum. etc (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean - note: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape, but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - REturn a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) #[height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0-> 1, 1-> 2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy


In [ ]:
# create a tensor
import torch
x = torch.arange(1, 10,).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions, but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension, but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]


tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimesion
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# index on x to return 9
x[0,2,2]

tensor(9)

In [ ]:
# inex on x to return 3, 6, 9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it

* Data in NumPy. want in PyTorch tensor-> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor



(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to `tensor`

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again....`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavor" the randomness


In [54]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1672, 0.4104, 0.5125, 0.7234],
        [0.4391, 0.8717, 0.7849, 0.8496],
        [0.3828, 0.0462, 0.1209, 0.1755]])
tensor([[0.2482, 0.4937, 0.6046, 0.7482],
        [0.3316, 0.9440, 0.0027, 0.8779],
        [0.8486, 0.6599, 0.4751, 0.5239]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [56]:
# Let's make some random, but reproducible tensors
import torch
# Set the random see
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes.

### 1. Getting a GPU

Skipped this section since I already set this up on my pc locally


In [57]:
torch.cuda.is_available()

True

In [58]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [59]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [61]:
# Create a tensor (Default is on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)



tensor([1, 2, 3]) cpu


In [62]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [63]:
# If tensor is on GPU, it can't be transformed to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [65]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [66]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-curriculum

In [69]:
import torch

# Create a random tensor with shape (7, 7)
exercise_tensor = torch.rand(7,7)
exercise_tensor.shape

torch.Size([7, 7])

In [116]:
#Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
other_tensor = torch.rand(1, 7)
torch.matmul(exercise_tensor, other_tensor.T)

tensor([[1.8041],
        [1.3687],
        [1.2985],
        [1.4879],
        [1.8693],
        [1.3046],
        [0.7703]])

In [117]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
exercise_tensor = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
other_tensor = torch.rand(1, 7)

torch.matmul(exercise_tensor, other_tensor.T)

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

In [119]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
GPU_RANDOM_SEED = 1234
torch.cuda.manual_seed(GPU_RANDOM_SEED)


In [120]:
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(2, 3)

torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(2, 3)

tensor_A_on_GPU = tensor_A.to("cuda")
tensor_B_on_GPU = tensor_B.to("cuda")

print(tensor_A_on_GPU, tensor_B_on_GPU)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


In [122]:
# Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
GPU_tensor_output = torch.matmul(tensor_A_on_GPU, tensor_B_on_GPU.T)
GPU_tensor_output

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [127]:
# Find the maximum and minimum values of the output of 7.
GPU_tensor_output.argmin()


tensor(1, device='cuda:0')

In [128]:
GPU_tensor_output[1]

tensor([0.2161, 0.6287], device='cuda:0')