## 00. Pytorch Fundamentals


In [292]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.1+cu130


In [293]:
print("Hello, I'm excited to learn PyTorch")

Hello, I'm excited to learn PyTorch


## Introduction to Tensors



### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`

In [294]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [295]:
# ndim = number of dimensions
scalar.ndim

0

In [296]:
# Get tensor back as Python int
scalar.item()

7

In [297]:
# Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [298]:
vector.ndim

1

In [299]:
vector.shape

torch.Size([2])

In [300]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [301]:
MATRIX.ndim


2

In [302]:
MATRIX[1]

tensor([ 9, 10])

In [303]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [304]:
TENSOR.ndim

3

In [305]:
TENSOR.shape

torch.Size([1, 3, 3])

In [306]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

![Tensor](images\tensor.png)

In [307]:
PRACTICE_TENSOR = torch.tensor([[[6,7,9,1],
                                 [5,3,2,0]],
                                [[1,1,1,1],
                                 [2,2,2,2]]])
PRACTICE_TENSOR

tensor([[[6, 7, 9, 1],
         [5, 3, 2, 0]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2]]])

In [308]:
PRACTICE_TENSOR.ndim

3

In [309]:
PRACTICE_TENSOR.shape

torch.Size([2, 2, 4])

### Random Tensors

Why Random tensors?

Random tensors are important because the wat many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> Update random numbers -> Look at data -> Update random numbers`

In [310]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6097, 0.9056, 0.0245, 0.2362],
        [0.4888, 0.9918, 0.8044, 0.7010],
        [0.9345, 0.4904, 0.6435, 0.1241]])

In [311]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, Width, Color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [312]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [313]:
# Create tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [314]:
ones.dtype

torch.float32

In [315]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like 

In [316]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [317]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you will run into with PyTorch & deep learning:
1. Tensors are not the right datatype
2. Tensors are not the right shape
3. Tensors are not on the right device

In [318]:
# FLoat 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32, float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients 
float_32_tensor

tensor([3., 6., 9.])

In [319]:
float_32_tensor.dtype

torch.float32

In [320]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [321]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [322]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [323]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. To get datatype from a tensor, can use `tensor.dtype`
2. To get shape from a tensor, can use `tensor.shape`
3. To get device from a tensor, can use `tensor.device`

In [324]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5202, 0.7381, 0.0146, 0.9324],
        [0.6629, 0.1462, 0.8895, 0.2828],
        [0.6753, 0.1264, 0.9535, 0.3880]])

In [325]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device that tensoris on: {some_tensor.device}")


tensor([[0.5202, 0.7381, 0.0146, 0.9324],
        [0.6629, 0.1462, 0.8895, 0.2828],
        [0.6753, 0.1264, 0.9535, 0.3880]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device that tensoris on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication 

In [326]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [327]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [328]:
tensor

tensor([1, 2, 3])

In [329]:
# subtract
tensor - 10

tensor([-9, -8, -7])

In [330]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [331]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The inner dimensions must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resultin matrix has the shape of the **outer dimensions**"
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [332]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.3637, 0.4216],
        [0.9107, 0.9433]])

In [333]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [334]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [335]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [336]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 703 μs


In [337]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 49.8 μs


tensor(14)

### One of the most common errors in deep learning: shape errors


In [340]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axis or dimensions of a given tensor.


In [344]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [345]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [353]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput: shape: {output.shape}")



Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]) (same shape), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output: shape: torch.Size([3, 3])


## Finding the min, max, mean, sum. etc (tensor aggregation)

In [360]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [356]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [357]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [364]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))