## 00. Pytorch Fundamentals


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.1+cu130


In [4]:
print("Hello, I'm excited to learn PyTorch")

Hello, I'm excited to learn PyTorch


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`

In [6]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# ndim = number of dimensions
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

<function Tensor.item()>

In [10]:
# Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim


torch.Size([2, 2])

In [21]:
MATRIX[1]

tensor([ 9, 10])

In [22]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

![Tensor](images\tensor.png)

In [27]:
PRACTICE_TENSOR = torch.tensor([[[6,7,9,1],
                                 [5,3,2,0]],
                                [[1,1,1,1],
                                 [2,2,2,2]]])
PRACTICE_TENSOR

tensor([[[6, 7, 9, 1],
         [5, 3, 2, 0]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2]]])

In [28]:
PRACTICE_TENSOR.ndim

3

In [29]:
PRACTICE_TENSOR.shape

torch.Size([2, 2, 4])